replicaCount: 3

image:
  repository: local/hello-world
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  externalPort: 443

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: letsencrypt
  path: /
  hosts:
    - example.com
  tls:
    - hosts:
      - example.com
      secretName: example-com-tls

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
